# Generated by Django 5.2.6 on 2025-09-30 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
